services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uptime-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uptime_monitor.db:/app/uptime_monitor.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: uptime_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    